### PR TITLE
Update composer.json to support PHP 7.4

### PR DESCRIPTION
**Pull request by Tantuss**
Added PHP 7.4 and removed old PHP versions which are not supported by Magento.

### CODE REVIEW

**Comment by leonhelmus** [comment]
Could this one be merged?

**Comment by nielsnoorlander** [comment]
This merge request is currently in review. We hope to merge this asap.

**Comment by nielsnoorlander** [comment]
And we'll also add PHP 8.x support.

**Comment by 808brinks** [comment]
I've looked into it and it seems that removing the php dependency completely would be the most future proof solution. This should also enable 8.x support.

A new pull request will be made with this change so I'm closing this one.

**Comment by 808brinks** [comment]
The new pull request: https://github.com/SpotlerSoftware/magento2-mailplus-connector/pull/23

**Comment by 808brinks** [comment]
The pull request #23 has been merged and released in  1.7.4

**Pull request closed without merging**
