### PR TITLE
PHP 7.1 compatibility + minor cleanup

### PR DESCRIPTION
**Pull request by riotrick**
Added php 7.1.0 to composer dependencies.
Added a missing  getList() method.
Removed an obsolete php closing tag.
Removed empty acl.xml

### CODE REVIEW

**Comment by riotrick** [comment]
This also fixes: https://github.com/SpotlerSoftware/magento2-mailplus-connector/issues/6

**Comment by PaulBoss** [comment]
We've merged these fixes directly in the 1.4.2 release. Thanks for the pull-request. We've skipped the change for adding the getList method in ExtendedOrderRepository since this method is already implemented by the parent class OrderRepository

**Comment by riotrick** [comment]
@PaulBoss Could you please update the version in the composer.json to 1.4.2 as well. Composer keeps trying to fetch the 1.4.1 tagged version, since that is the version in the composer.json file.

**Comment by PaulBoss** [comment]
@riotrick This is fixed now. A new version 1.4.3 is released where the only difference is the version number.

**Pull request closed without merging**
